apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-jenkins-webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/crnksl/kubevela-argocd-jenkins.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true




